# Font configuration
font:
        normal:
                family: Hack
                style: Regular

        # Point size
        size: 10

        # Offset is the extra space around each character. `offset.y` can be thought of
        # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
        offset:
            x: 0
            y: 0
cursor:
        # Cursor style
        # Values for `style`:
        #   - â–‡ Block
        #   - _ Underline
        #   - | Beam
        style: Beam

# Colors
colors:
    primary:
        background: '#2f383e'
        foreground: '#d3c6aa'
    normal:
        black:   '#4b565c'
        red:     '#e67e80'
        green:   '#a7c080'
        yellow:  '#dbbc7f'
        blue:    '#7fbbb3'
        magenta: '#d699b6'
        cyan:    '#83c092'
        white:   '#d3c6aa'
    bright:
        black:   '#4b565c'
        red:     '#e67e80'
        green:   '#a7c080'
        yellow:  '#dbbc7f'
        blue:    '#7fbbb3'
        magenta: '#d699b6'
        cyan:    '#83c092'
        white:   '#d3c6aa'

window:
        # Window padding (changes require restart)
        # Blank space added around the window in pixels. This padding is scaled
        # by DPI and the specified value is always added at both opposing sides.
        padding:
                x: 3
                y: 3

        # Spread additional padding evenly around the terminal content.
        dynamic_padding: true
